name: Deploy Flask App to Azure

on:
  push:
    branches:
      - backend-only  # Branch name for your backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Match your Azure runtime stack

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Archive application
      run: zip -r app.zip .

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: "loadminds"  # Your Azure App Service name
        package: "./app.zip"
