name: Build and Deploy to Azure App Service

on:
  push:
    branches:
      - backend-only  # Replace with your backend branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Use your Flask app's Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Archive app
      run: zip -r flaskapp.zip .

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: "<your-app-name>"  # Replace with your Azure App Service name
        slot-name: 'production'
        package: './flaskapp.zip'
